### ISSUE TITLE
Emails are not sent

### ISSUE THREAD

**Issue by Bufka2011** [CoolCat467/MineOS-Market-Server#24]
![image](https://github.com/user-attachments/assets/383ec207-4f8b-4e97-af22-1ac7fe46dff5)

"Check your email and "spam" folder to approve your account"

But email is empty.

**Comment by CoolCat467** [comment]
Sending actual emails is not implemented yet, so for the moment in the logs of the server it prints out what it wanted to send as an email, and the link you need is in there.

**Comment by Bufka2011** [comment]
Thank you!

**Comment by Bufka2011** [comment]
Sorry to bother you, but where are the apps themselves?

![image](https://github.com/user-attachments/assets/dbdc86d7-fd33-49fc-9c9c-27e156e5cd29)

Here is nothing.+

**Comment by Bufka2011** [comment]
And I found a bug. At least I think so.

![image](https://github.com/user-attachments/assets/795ce5a9-332f-4e86-a5c6-8e2143d245c7)

This is I press a "Main" (I think) button

![image](https://github.com/user-attachments/assets/0b608a20-68f0-4d1c-b8fc-a4bc7dcb9af0)

**Comment by CoolCat467** [comment]
App market itself has a bug handling zero publications in overview tab, which https://github.com/IgorTimofeev/MineOS/pull/629 was fixing, but it hasn't been kept. https://github.com/CoolCat467/MineOS-Market-Server#why-are-there-no-publications is the reason why no publications exist.

**Comment by Bufka2011** [comment]
I understand, but where is the server records folder?
